import 'package:flutter/material.dart';

import '../../domain/models/fixture_generation_options.dart';

/// Result of the fixture autogenerate dialog.
class FixtureAutogenerateResult {
  const FixtureAutogenerateResult({required this.options, this.confirmed = false});
  final FixtureGenerationOptions options;
  final bool confirmed;
}

/// Dialog for configuring and confirming fixture auto-generation.
class FixtureAutogenerateDialog extends StatefulWidget {
  const FixtureAutogenerateDialog({
    super.key,
    required this.seasonId,
    required this.leagueId,
    required this.seasonName,
    required this.defaultVenue,
    this.defaultVenueImageUrl,
    required this.activeTeamCount,
  });

  final String seasonId;
  final String leagueId;
  final String seasonName;
  final String? defaultVenue;
  final String? defaultVenueImageUrl;
  final int activeTeamCount;

  static Future<FixtureAutogenerateResult?> show(
    BuildContext context, {
    required String seasonId,
    required String leagueId,
    required String seasonName,
    String? defaultVenue,
    String? defaultVenueImageUrl,
    required int activeTeamCount,
  }) {
    return showDialog<FixtureAutogenerateResult>(
      context: context,
      builder: (ctx) => FixtureAutogenerateDialog(
        seasonId: seasonId,
        leagueId: leagueId,
        seasonName: seasonName,
        defaultVenue: defaultVenue,
        defaultVenueImageUrl: defaultVenueImageUrl,
        activeTeamCount: activeTeamCount,
      ),
    );
  }

  @override
  State<FixtureAutogenerateDialog> createState() =>
      _FixtureAutogenerateDialogState();
}

class _FixtureAutogenerateDialogState extends State<FixtureAutogenerateDialog> {
  FixtureFormat _fixtureFormat = FixtureFormat.singleLeg;
  HomeAwayMode _homeAwayMode = HomeAwayMode.homeAway;
  DateTime? _firstGameweekDate;
  int _gameweekIntervalDays = 7;
  SchedulingMode _schedulingMode = SchedulingMode.weekly;
  bool _sameDayMatches = false;
  TimeOfDay _startTime = const TimeOfDay(hour: 9, minute: 0);
  TimeOfDay _endTime = const TimeOfDay(hour: 18, minute: 0);
  bool _sameTimeForAll = false;
  bool _allowRegeneration = false;
  int _compressedLeagueDays = 1;
  bool _fullRoundPerGameweek = false;
  int _fullRoundGameweeksPerLeg = 1;

  int get _singleLegMatches =>
      widget.activeTeamCount < 2
          ? 0
          : widget.activeTeamCount * (widget.activeTeamCount - 1) ~/ 2;
  int get _matchesPerGameweek => _singleLegMatches;
  int get _totalMatches {
    if (!_fullRoundPerGameweek) {
      return _fixtureFormat == FixtureFormat.doubleLeg
          ? _singleLegMatches * 2
          : _singleLegMatches;
    }
    final gw = _fullRoundGameweeksPerLeg * (_fixtureFormat == FixtureFormat.doubleLeg ? 2 : 1);
    return _matchesPerGameweek * gw;
  }

  int get _gameweeksPerLeg {
    if (_fullRoundPerGameweek) return _fullRoundGameweeksPerLeg;
    final n = widget.activeTeamCount;
    if (n < 2) return 0;
    return n.isOdd ? n : n - 1;
  }

  int get _totalGameweeks =>
      _fixtureFormat == FixtureFormat.doubleLeg
          ? _gameweeksPerLeg * 2
          : _gameweeksPerLeg;

  FixtureGenerationOptions _buildOptions() {
    final startTimeStr =
        '${_startTime.hour.toString().padLeft(2, '0')}:${_startTime.minute.toString().padLeft(2, '0')}';
    final endTimeStr =
        '${_endTime.hour.toString().padLeft(2, '0')}:${_endTime.minute.toString().padLeft(2, '0')}';
    return FixtureGenerationOptions(
      seasonId: widget.seasonId,
      leagueId: widget.leagueId,
      fixtureFormat: _fixtureFormat,
      homeAwayMode: _homeAwayMode,
      firstGameweekDate: _firstGameweekDate!,
      gameweekIntervalDays: _gameweekIntervalDays,
      schedulingMode: _schedulingMode,
      sameDayMatches: _sameDayMatches,
      startTime: _sameDayMatches ? startTimeStr : null,
      endTime: _sameDayMatches && !_sameTimeForAll ? endTimeStr : null,
      defaultVenue: widget.defaultVenue ?? 'TBD',
      defaultVenueImageUrl: widget.defaultVenueImageUrl,
      allowRegeneration: _allowRegeneration,
      sameTimeForAll: _sameTimeForAll,
      compressedLeagueDays:
          _schedulingMode == SchedulingMode.compressed ? _compressedLeagueDays : null,
      fullRoundPerGameweek: _fullRoundPerGameweek,
      fullRoundGameweeksPerLeg: _fullRoundPerGameweek
          ? _fullRoundGameweeksPerLeg.clamp(1, 999)
          : null,
    );
  }

  bool get _canGenerate =>
      _firstGameweekDate != null &&
      widget.activeTeamCount >= 2;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return AlertDialog(
      title: const Text('Auto-generate fixtures'),
      content: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              'Season: ${widget.seasonName}',
              style: theme.textTheme.titleSmall,
            ),
            Text(
              '${widget.activeTeamCount} active teams → $_totalMatches matches, $_totalGameweeks gameweeks',
              style: theme.textTheme.bodySmall,
            ),
            const SizedBox(height: 16),
            _sectionTitle(theme, 'Fixture format'),
            SegmentedButton<FixtureFormat>(
              segments: const [
                ButtonSegment(value: FixtureFormat.singleLeg, label: Text('Single-leg')),
                ButtonSegment(value: FixtureFormat.doubleLeg, label: Text('Double-leg')),
              ],
              selected: {_fixtureFormat},
              onSelectionChanged: (s) => setState(() => _fixtureFormat = s.first),
            ),
            const SizedBox(height: 8),
            _sectionTitle(theme, 'Home/Away'),
            SegmentedButton<HomeAwayMode>(
              segments: const [
                ButtonSegment(value: HomeAwayMode.homeAway, label: Text('Home/Away')),
                ButtonSegment(value: HomeAwayMode.neutral, label: Text('Neutral')),
              ],
              selected: {_homeAwayMode},
              onSelectionChanged: (s) => setState(() => _homeAwayMode = s.first),
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                Checkbox(
                  value: _fullRoundPerGameweek,
                  onChanged: (v) => setState(() => _fullRoundPerGameweek = v ?? false),
                ),
                const Expanded(
                  child: Text(
                    'Full round (all pairs, spread across gameweeks)',
                    style: TextStyle(fontSize: 12),
                  ),
                ),
              ],
            ),
            if (_fullRoundPerGameweek) ...[
              const SizedBox(height: 8),
              _sectionTitle(theme, 'Gameweeks per leg'),
              Text(
                'Each gameweek: every team plays every other once ($_matchesPerGameweek matches). '
                'Order avoids back-to-back (no team in consecutive matches).',
                style: theme.textTheme.bodySmall,
              ),
              const SizedBox(height: 4),
              DropdownButtonFormField<int>(
                initialValue: _fullRoundGameweeksPerLeg.clamp(1, 52),
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  contentPadding: EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                ),
                items: List.generate(52, (i) => i + 1)
                    .map((v) => DropdownMenuItem(value: v, child: Text('$v')))
                    .toList(),
                onChanged: (v) =>
                    setState(() => _fullRoundGameweeksPerLeg = v ?? 1),
              ),
              const SizedBox(height: 4),
            ],
            const SizedBox(height: 16),
            _sectionTitle(theme, 'First gameweek date'),
            OutlinedButton(
              onPressed: () async {
                final d = await showDatePicker(
                  context: context,
                  initialDate: _firstGameweekDate ?? DateTime.now(),
                  firstDate: DateTime.now(),
                  lastDate: DateTime.now().add(const Duration(days: 365)),
                );
                if (d != null) setState(() => _firstGameweekDate = d);
              },
              child: Text(
                _firstGameweekDate == null
                    ? 'Pick date'
                    : '${_firstGameweekDate!.day}/${_firstGameweekDate!.month}/${_firstGameweekDate!.year}',
              ),
            ),
            const SizedBox(height: 16),
            _sectionTitle(theme, 'Gameweek interval (days)'),
            SegmentedButton<int>(
              segments: const [
                ButtonSegment(value: 4, label: Text('4')),
                ButtonSegment(value: 7, label: Text('7')),
                ButtonSegment(value: 14, label: Text('14')),
              ],
              selected: {_gameweekIntervalDays},
              onSelectionChanged: (s) => setState(() => _gameweekIntervalDays = s.first),
            ),
            const SizedBox(height: 16),
            _sectionTitle(theme, 'Scheduling mode'),
            DropdownButtonFormField<SchedulingMode>(
              initialValue: _schedulingMode,
              items: const [
                DropdownMenuItem(value: SchedulingMode.weekly, child: Text('Weekly')),
                DropdownMenuItem(value: SchedulingMode.biweekly, child: Text('Biweekly')),
                DropdownMenuItem(value: SchedulingMode.twicePerWeek, child: Text('Twice per week')),
                DropdownMenuItem(value: SchedulingMode.compressed, child: Text('Compressed')),
              ],
              onChanged: (v) => setState(() {
                _schedulingMode = v ?? SchedulingMode.weekly;
                if (_schedulingMode == SchedulingMode.biweekly) {
                  _gameweekIntervalDays = 14;
                } else if (_schedulingMode == SchedulingMode.weekly) {
                  _gameweekIntervalDays = 7;
                } else if (_schedulingMode == SchedulingMode.twicePerWeek) {
                  _gameweekIntervalDays = 4;
                }
              }),
            ),
            if (_schedulingMode == SchedulingMode.compressed) ...[
              const SizedBox(height: 8),
              _sectionTitle(theme, 'Compressed league days'),
              SegmentedButton<int>(
                segments: const [
                  ButtonSegment(value: 1, label: Text('1 day')),
                  ButtonSegment(value: 2, label: Text('2 days')),
                  ButtonSegment(value: 3, label: Text('3 days')),
                ],
                selected: {_compressedLeagueDays},
                onSelectionChanged: (s) => setState(() => _compressedLeagueDays = s.first),
              ),
            ],
            const SizedBox(height: 16),
            Row(
              children: [
                Checkbox(
                  value: _sameDayMatches,
                  onChanged: (v) => setState(() => _sameDayMatches = v ?? false),
                ),
                const Text('Same-day matches in gameweek'),
              ],
            ),
            if (_sameDayMatches) ...[
              Row(
                children: [
                  Checkbox(
                    value: _sameTimeForAll,
                    onChanged: (v) => setState(() => _sameTimeForAll = v ?? false),
                  ),
                  const Text('Same kick-off for all'),
                ],
              ),
              if (!_sameTimeForAll) ...[
                ListTile(
                  title: Text('Start: ${_startTime.format(context)}'),
                  trailing: TextButton(
                    onPressed: () async {
                      final t = await showTimePicker(
                        context: context,
                        initialTime: _startTime,
                      );
                      if (t != null) setState(() => _startTime = t);
                    },
                    child: const Text('Change'),
                  ),
                ),
                ListTile(
                  title: Text('End: ${_endTime.format(context)}'),
                  trailing: TextButton(
                    onPressed: () async {
                      final t = await showTimePicker(
                        context: context,
                        initialTime: _endTime,
                      );
                      if (t != null) setState(() => _endTime = t);
                    },
                    child: const Text('Change'),
                  ),
                ),
              ],
            ],
            const SizedBox(height: 8),
            Row(
              children: [
                Checkbox(
                  value: _allowRegeneration,
                  onChanged: (v) => setState(() => _allowRegeneration = v ?? false),
                ),
                const Expanded(
                  child: Text(
                    'Allow regeneration (replace existing fixtures)',
                    style: TextStyle(fontSize: 12),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(null),
          child: const Text('Cancel'),
        ),
        FilledButton(
          onPressed: _canGenerate
              ? () => Navigator.of(context).pop(
                    FixtureAutogenerateResult(
                      options: _buildOptions(),
                      confirmed: true,
                    ),
                  )
              : null,
          child: const Text('Generate'),
        ),
      ],
    );
  }

  Widget _sectionTitle(ThemeData theme, String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Text(text, style: theme.textTheme.labelMedium),
    );
  }
}
