import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../providers/league_teams_provider.dart';
import '../providers/matches_provider.dart';
import '../providers/seasons_provider.dart';
import '../../domain/models/season_model.dart';
import '../../domain/models/team_model.dart';
import 'fixture.dart';

class LeagueCreateMatchesPage extends ConsumerStatefulWidget {
  const LeagueCreateMatchesPage({super.key, required this.leagueId});

  final String leagueId;

  @override
  ConsumerState<LeagueCreateMatchesPage> createState() =>
      _LeagueCreateMatchesPageState();
}

class _LeagueCreateMatchesPageState
    extends ConsumerState<LeagueCreateMatchesPage> {
  final _formKey = GlobalKey<FormState>();
  final _venueController = TextEditingController();
  TeamModel? _teamA;
  TeamModel? _teamB;
  DateTime? _matchDate;
  TimeOfDay? _matchTime;
  SeasonModel? _season;
  bool _isSubmitting = false;

  @override
  void dispose() {
    _venueController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final now = DateTime.now();
    final date = await showDatePicker(
      context: context,
      initialDate: _matchDate ?? now,
      firstDate: now.subtract(const Duration(days: 365)),
      lastDate: now.add(const Duration(days: 365)),
    );
    if (date != null) setState(() => _matchDate = date);
  }

  Future<void> _pickTime() async {
    final time = await showTimePicker(
      context: context,
      initialTime: _matchTime ?? const TimeOfDay(hour: 15, minute: 0),
    );
    if (time != null) setState(() => _matchTime = time);
  }

  Future<void> _createMatch() async {
    final isValid = _formKey.currentState?.validate() ?? false;
    if (!isValid || _teamA == null || _teamB == null || _season == null) return;
    if (_teamA!.id == _teamB!.id) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Pick two different teams')),
      );
      return;
    }
    if (_matchDate == null || _matchTime == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Pick a date and time')),
      );
      return;
    }
    final venue = _venueController.text.trim();
    if (venue.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Enter a venue')),
      );
      return;
    }

    setState(() => _isSubmitting = true);
    try {
      final repo = ref.read(matchesRepositoryProvider);
      final timeStr =
          '${_matchTime!.hour.toString().padLeft(2, '0')}:${_matchTime!.minute.toString().padLeft(2, '0')}';
      final id = await repo.createMatch(
        leagueId: widget.leagueId,
        seasonId: _season!.id,
        teamAId: _teamA!.id,
        teamBId: _teamB!.id,
        matchDate: _matchDate!,
        matchTime: timeStr,
        venue: venue,
      );
      if (!mounted) return;
      ref.invalidate(matchesProvider);
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(builder: (_) => FixturePage(matchId: id)),
      );
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Match created')),
      );
    } catch (error) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error creating match: $error')),
      );
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  Future<void> _showAutoGenerateDialog(List<TeamModel> teams) async {
    DateTime? startDate;
    DateTime? endDate;
    TimeOfDay matchTime = const TimeOfDay(hour: 15, minute: 0);

    final result = await showDialog<bool>(
      context: context,
      builder: (ctx) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              title: const Text('Auto-generate fixtures'),
              content: SingleChildScrollView(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    const Text(
                      'Generate round-robin matches between all league teams.',
                      style: TextStyle(fontSize: 14),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      '${teams.length} teams = ${teams.length * (teams.length - 1) ~/ 2} matches',
                      style: Theme.of(ctx).textTheme.bodySmall,
                    ),
                    const SizedBox(height: 16),
                    OutlinedButton(
                      onPressed: () async {
                        final now = DateTime.now();
                        final d = await showDatePicker(
                          context: ctx,
                          initialDate: startDate ?? now,
                          firstDate: now,
                          lastDate: now.add(const Duration(days: 365)),
                        );
                        if (d != null) {
                          setDialogState(() => startDate = d);
                        }
                      },
                      child: Text(
                        startDate == null
                            ? 'Start date'
                            : '${startDate!.year}-${startDate!.month.toString().padLeft(2, '0')}-${startDate!.day.toString().padLeft(2, '0')}',
                      ),
                    ),
                    const SizedBox(height: 8),
                    OutlinedButton(
                      onPressed: () async {
                        final now = DateTime.now();
                        final d = await showDatePicker(
                          context: ctx,
                          initialDate: endDate ?? startDate ?? now,
                          firstDate: startDate ?? now,
                          lastDate: (startDate ?? now)
                              .add(const Duration(days: 365)),
                        );
                        if (d != null) {
                          setDialogState(() => endDate = d);
                        }
                      },
                      child: Text(
                        endDate == null
                            ? 'End date'
                            : '${endDate!.year}-${endDate!.month.toString().padLeft(2, '0')}-${endDate!.day.toString().padLeft(2, '0')}',
                      ),
                    ),
                    const SizedBox(height: 8),
                    OutlinedButton(
                      onPressed: () async {
                        final t = await showTimePicker(
                          context: ctx,
                          initialTime: matchTime,
                        );
                        if (t != null) {
                          setDialogState(() => matchTime = t);
                        }
                      },
                      child: Text('Match time: ${matchTime.format(ctx)}'),
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.of(ctx).pop(false),
                  child: const Text('Cancel'),
                ),
                FilledButton(
                  onPressed: (startDate != null && endDate != null)
                      ? () => Navigator.of(ctx).pop(true)
                      : null,
                  child: const Text('Generate'),
                ),
              ],
            );
          },
        );
      },
    );

    if (result != true || !mounted || _season == null) return;
    if (startDate == null || endDate == null) return;
    if (endDate!.isBefore(startDate!)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('End date must be after start date')),
      );
      return;
    }

    setState(() => _isSubmitting = true);
    try {
      final repo = ref.read(matchesRepositoryProvider);
      final timeStr =
          '${matchTime.hour.toString().padLeft(2, '0')}:${matchTime.minute.toString().padLeft(2, '0')}';
      final count = await repo.autoGenerateFixtures(
        leagueId: widget.leagueId,
        seasonId: _season!.id,
        startDate: startDate!,
        endDate: endDate!,
        matchTime: timeStr,
      );
      if (!mounted) return;
      ref.invalidate(matchesProvider);
      Navigator.of(context).pop();
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('$count matches created')),
      );
    } catch (error) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error generating fixtures: $error')),
      );
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final teamsAsync = ref.watch(teamsInLeagueProvider(widget.leagueId));
    final seasonAsync =
        ref.watch(ongoingOrUpcomingSeasonProvider(widget.leagueId));
    final textTheme = Theme.of(context).textTheme;
    final colorScheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: Text('Create match', style: textTheme.headlineMedium),
        centerTitle: false,
      ),
      body: teamsAsync.when(
        data: (teams) {
          if (teams.length < 2) {
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Text(
                  'Add at least 2 teams to the league before creating matches.',
                  style: textTheme.bodyLarge?.copyWith(
                    color: colorScheme.onSurfaceVariant,
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
            );
          }
          return seasonAsync.when(
            data: (season) {
              if (season == null) {
                return Center(
                  child: Padding(
                    padding: const EdgeInsets.all(24),
                    child: Text(
                      'Create a new season for this league first.',
                      style: textTheme.bodyLarge?.copyWith(
                        color: colorScheme.onSurfaceVariant,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ),
                );
              }
              if (_season == null) {
                WidgetsBinding.instance.addPostFrameCallback((_) {
                  if (mounted) setState(() => _season = season);
                });
              }
              return SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    Container(
                      decoration: BoxDecoration(
                        color: colorScheme.surfaceContainerHigh,
                        borderRadius: BorderRadius.circular(28),
                      ),
                      padding: const EdgeInsets.all(16),
                      child: Form(
                        key: _formKey,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('Match details', style: textTheme.titleMedium),
                            const SizedBox(height: 8),
                            Text(
                              'Season: ${season.seasonName}',
                              style: textTheme.bodySmall?.copyWith(
                                color: colorScheme.onSurfaceVariant,
                              ),
                            ),
                            const SizedBox(height: 16),
                            DropdownButtonFormField<TeamModel>(
                              initialValue: _teamA,
                              items: teams
                                  .map(
                                    (t) => DropdownMenuItem(
                                      value: t,
                                      child: Text(t.displayName),
                                    ),
                                  )
                                  .toList(),
                              onChanged: (value) =>
                                  setState(() => _teamA = value),
                              decoration: const InputDecoration(
                                labelText: 'Team A',
                                border: OutlineInputBorder(),
                              ),
                              validator: (value) =>
                                  value == null ? 'Select Team A' : null,
                            ),
                            const SizedBox(height: 12),
                            DropdownButtonFormField<TeamModel>(
                              initialValue: _teamB,
                              items: teams
                                  .map(
                                    (t) => DropdownMenuItem(
                                      value: t,
                                      child: Text(t.displayName),
                                    ),
                                  )
                                  .toList(),
                              onChanged: (value) =>
                                  setState(() => _teamB = value),
                              decoration: const InputDecoration(
                                labelText: 'Team B',
                                border: OutlineInputBorder(),
                              ),
                              validator: (value) =>
                                  value == null ? 'Select Team B' : null,
                            ),
                            const SizedBox(height: 16),
                            TextFormField(
                              controller: _venueController,
                              decoration: const InputDecoration(
                                labelText: 'Venue',
                                hintText: 'e.g. Main Stadium',
                                border: OutlineInputBorder(),
                              ),
                              validator: (value) {
                                if (value == null || value.trim().isEmpty) {
                                  return 'Enter a venue';
                                }
                                return null;
                              },
                            ),
                            const SizedBox(height: 16),
                            Row(
                              children: [
                                Expanded(
                                  child: OutlinedButton(
                                    onPressed: _pickDate,
                                    child: Text(
                                      _matchDate == null
                                          ? 'Pick date'
                                          : '${_matchDate!.year}-${_matchDate!.month.toString().padLeft(2, '0')}-${_matchDate!.day.toString().padLeft(2, '0')}',
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: OutlinedButton(
                                    onPressed: _pickTime,
                                    child: Text(
                                      _matchTime == null
                                          ? 'Pick time'
                                          : _matchTime!.format(context),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 20),
                            SizedBox(
                              width: double.infinity,
                              child: FilledButton(
                                onPressed:
                                    _isSubmitting ? null : _createMatch,
                                child: _isSubmitting
                                    ? const SizedBox(
                                        width: 20,
                                        height: 20,
                                        child: CircularProgressIndicator(
                                          strokeWidth: 2,
                                        ),
                                      )
                                    : const Text('Create match'),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    OutlinedButton.icon(
                      onPressed: _isSubmitting
                          ? null
                          : () => _showAutoGenerateDialog(teams),
                      icon: const Icon(Icons.auto_awesome),
                      label: const Text('Auto-generate fixtures'),
                    ),
                  ],
                ),
              );
            },
            loading: () =>
                const Center(child: CircularProgressIndicator()),
            error: (err, _) => Center(child: Text('Error: $err')),
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (err, _) => Center(child: Text('Error: $err')),
      ),
    );
  }
}
